name: Wiki updated

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main/source/**'
      - 'wiki/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      python-version: 3.x

    steps:
    - uses: actions/checkout@v2
      with:
        path: ./nl_mcm

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: PaPyDoc repo
      uses: actions/checkout@v4
      with:
        repository: MrOctopus/PaPyDoc
        path: ./PaPyDoc

    - name: Run PaPyDoc and generate wiki documentation
      run: python ./PaPyDoc/run.py -o "./nl_mcm/wiki" "./nl_mcm/main/source/**"
      
    - name: Push wiki changes
      if: success()
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      with:
        path: ./nl_mcm/wiki/